src/accounts/urls.py
from accounts.views import AccountLoginView, AccountLogoutView, AccountRegistrationView, AccountUpdateView, \
    ChangePasswordView

import debug_toolbar # noqa
from django.contrib import admin # noqa
from django.urls import path, include # noqa

app_name = 'accounts'

urlpatterns = [
    path('registration', AccountRegistrationView.as_view(), name='registration'),
    path('login', AccountLoginView.as_view(), name='login'),
    path('logout', AccountLogoutView.as_view(), name='logout'),
    path('profile', AccountUpdateView.as_view(), name='profile'),
    path('password', ChangePasswordView.as_view(), name='password')
]

src/groups/urls.py
from django.conf import settings # noqa
from django.urls import include, path # noqa

from groups.views import GroupCreateView, GroupDeleteView, GroupListView, GroupUpdateView

app_name = 'groups'

urlpatterns = [
    path('', GroupListView.as_view(), name='list'),
    path('create', GroupCreateView.as_view(), name='create'),
    path('update/<int:id>', GroupUpdateView.as_view(), name='update'),
    path('delete/<int:id>', GroupDeleteView.as_view(), name='delete'),
]

src/lms/urls.py
from core.views import index

import debug_toolbar

from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings # noqa
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', index, name='index'),

    path('students/', include('students.urls')),
    path('accounts/', include('accounts.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('classrooms/', include('classrooms.urls')),

    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/students/urls.py
from django.conf import settings # noqa
from django.urls import include, path # noqa

from students.views import StudentCreateView, StudentDeleteView, StudentListView, StudentUpdateView

app_name = "students"

urlpatterns = [
    path('', StudentListView.as_view(), name='list'),
    path('create', StudentCreateView.as_view(), name='create'),
    path('update/<int:id>', StudentUpdateView.as_view(), name='update'),
    path('delete/<int:id>', StudentDeleteView.as_view(), name='delete'),
]

src/teachers/urls.py
from django.conf import settings # noqa
from django.urls import include, path # noqa

from teachers.views import TeacherCreateView, TeacherDeleteView, TeacherListView, TeacherUpdateView

app_name = "teachers"

urlpatterns = [
    path('', TeacherListView.as_view(), name='list'),
    path('create', TeacherCreateView.as_view(), name='create'),
    path('update/<int:id>', TeacherUpdateView.as_view(), name='update'),
    path('delete/<int:id>', TeacherDeleteView.as_view(), name='delete')
]

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>LMS</title>
</head>
<body>



<nav class="navbar navbar-default navbar-fixed-top navbar-expand-lg navbar-dark bg-primary font-weight-bold ">

    <div class="container">

    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'students:list' %}">LMS</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">

            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'students:list' %}">Students</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'teachers:list' %}">Teachers</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'groups:list' %}">Groups</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'students:list' %}">About us</a>
            </li>
          </ul>
        </div>

        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                      <a class="nav-link active" aria-current="page" href="{% url 'accounts:profile' %}">Profile ({{ user.username }})</a>
                    </li>

                    <li class="nav-item">
                      <a class="nav-link active" aria-current="page" href="{% url 'accounts:logout' %}">Log out</a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:profile' %}"><img class="rounded-circle p-1 m-1"  src="{{user.profile.image.url}}" width="40px"></a>
                    </li>
                {% else %}

                    <li class="nav-item">
                      <a class="nav-link active" aria-current="page" href="{% url 'accounts:registration' %}">Registration</a>
                    </li>

                    <li class="nav-item">
                      <a class="nav-link active" aria-current="page" href="{% url 'accounts:login' %}">Log in</a>
                    </li>

                {% endif %}
            </ul>

      </div>
    </div>


</nav>


    <div class="container">

        {% include 'includes/messages.html' %}

        <div class="border rounded text-center p-3 m-3 bg-light text-dark">
            {% block header %}
                <h1> Welcome to LMS! </h1>
            {% endblock %}
        </div>

        {% block main %}
        {% endblock %}
    </div>

</body>
</html>

src/templates/index.html
{% extends 'base.html' %}

{% block main %}

<br>
<a href="{% url 'students:list' %}">Students</a>

{% endblock %}