src/lms/urls.py
from core.views import index

import debug_toolbar

from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings # noqa
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', index, name='index'),

    path('students/', include('students.urls')),
    path('accounts/', include('accounts.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('classrooms/', include('classrooms.urls')),

    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/teachers/urls.py
from django.conf import settings # noqa
from django.urls import include, path # noqa

from teachers.views import TeacherCreateView, TeacherDeleteView, TeacherListView, TeacherUpdateView

app_name = "teachers"

urlpatterns = [
    path('', TeacherListView.as_view(), name='list'),
    path('create', TeacherCreateView.as_view(), name='create'),
    path('update/<int:id>', TeacherUpdateView.as_view(), name='update'),
    path('delete/<int:id>', TeacherDeleteView.as_view(), name='delete')
]

src/teachers/models.py
import random

from core.models import Person

from courses.models import Course

from django.db import models

from groups.models import Group


class Teacher(Person):
    class LEVEL(models.IntegerChoices):
        ASSISTANT = 0, "Assistant"
        ASSOCIATE = 1, "Associate"
        PROFESSOR = 2, "Professor"

    group = models.ForeignKey(
        to=Group,
        null=True,
        on_delete=models.SET_NULL,
        related_name='teachers'
    )

    course = models.ManyToManyField(
        to=Course,
        related_name='teachers_course'
    )

    level = models.PositiveSmallIntegerField(
        choices=LEVEL.choices,
        default=LEVEL.ASSOCIATE
    )

    @classmethod
    def _generate(cls):
        obj = super()._generate()
        obj.level = random.choice(cls.LEVEL.values)
        obj.save()

    def __str__(self):
        return f'{self.first_name} {self.last_name}, {self.age}'

src/teachers/forms.py
import re # noqa

import django_filters
from django.core.exceptions import ValidationError # noqa
from django.forms import ModelForm

from email_validator import EmailNotValidError, validate_email

from teachers.models import Teacher


class TeacherFilter(django_filters.FilterSet):

    class Meta:

        model = Teacher
        fields = {
            'age': ['lt', 'gt'],
            'first_name': ['exact', 'icontains'],
            'last_name': ['exact', 'startswith'],
        }


class TeacherBaseForm(ModelForm):

    class Meta:
        model = Teacher
        # fields = ['first_name', 'last_name', 'age']
        fields = '__all__'

    def as_div(self):
        "Return this form rendered as HTML <p>s."
        return self._html_output(
            normal_row='<p%(html_class_attr)s>%(label)s %(field)s%(help_text)s</p>',
            error_row='%s',
            row_ender='</p>',
            help_text_html=' <span class="helptext">%s</span>',
            errors_on_separate_row=True,
        )

    def clean_phone_number(self):
        SHORT_LENGTH = 13 # noqa

        phone_number = self.cleaned_data['phone_number']

        pattern = '(\(\d\d\d\)|\+\d\d\(\d\d\d\))\d\d\d\-\d\d\d\d' # noqa

        if not re.match(pattern, phone_number):
            raise ValidationError('Phone number is not correct')

        if len(phone_number) == SHORT_LENGTH:
            phone_number = '+38' + phone_number

        return phone_number

    def clean_age(self):
        employment_age = 50

        if self.cleaned_data['age'] > employment_age:
            raise ValidationError('Too old')

    def clean_email(self):

        BLACKLIST = ['asd.com'] # noqa

        email = self.cleaned_data['email']

        try:
            valid = validate_email(email)
            email = valid.email
            domain = valid.domain
            if domain in BLACKLIST:
                raise ValidationError('Your domain is prohibited')
        except EmailNotValidError:
            raise ValidationError('Email is invalid')

        teachers = Teacher.objects.filter(email=email).exclude(id=self.instance.id)

        if teachers:
            raise ValidationError('Email is not unique')

        return email


class TeacherCreateForm(TeacherBaseForm):
    pass


class TeacherUpdateForm(TeacherBaseForm):
    class Meta(TeacherBaseForm.Meta):
        exclude = ['age']

src/teachers/views.py
from copy import copy

from django.db.models import Q # noqa
from django.http import HttpResponse, HttpResponseRedirect # noqa
from django.shortcuts import render, get_object_or_404  # noqa
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from teachers.forms import TeacherBaseForm, TeacherCreateForm, TeacherFilter, TeacherUpdateForm
from teachers.models import Teacher


def get_teachers(request):
    teachers = Teacher.objects.all().select_related('group').order_by('-id')

    filter = TeacherFilter( # noqa
        data=request.GET,
        queryset=teachers,
    )

    # params = [
    #     'first_name',
    #     'first_name__startswith',
    #     'first_name__endswith',
    #     'last_name',
    #     'age',
    #     'age__gt'
    # ]
    #
    # for param_name in params:
    #     param_value = request.GET.get(param_name)
    #     if param_value:
    #         param_elems = param_value.split(',')
    #         if param_elems:
    #             or_filter = Q()
    #             for param_elem in param_elems:
    #                 or_filter |= Q(**{param_name: param_elem})
    #             teachers = teachers.filter(or_filter)
    #         else:
    #             teachers = teachers.filter(**{param_name: param_value})

    return render(request=request,
                  template_name='teachers-list.html',
                  context={'filter': filter})


def create_teacher(request):
    if request.method == 'POST':

        form = TeacherCreateForm(request.POST)

        if form.is_valid():
            form.save()

            return HttpResponseRedirect(reverse('teachers:list'))

    else:

        form = TeacherCreateForm()

    return render(request=request,
                  template_name='teachers-create.html',
                  context={'form': form})


def update_teacher(request, id): # noqa
    teacher = Teacher.objects.get(id=id)

    if request.method == 'POST':

        form = TeacherUpdateForm(
            data=request.POST,
            instance=teacher
        )

        if form.is_valid():
            form.save()

            return HttpResponseRedirect(reverse('teachers:list'))

    else:

        form = TeacherUpdateForm(instance=teacher)

    return render(request=request,
                  template_name='teachers-update.html',
                  context={'form': form})


def delete_teacher(request, id): # noqa
    teacher = get_object_or_404(Teacher, id=id)

    if request.method == 'POST':
        teacher.delete()
        return HttpResponseRedirect(reverse('teachers:list'))

    return render(
        request=request,
        template_name='teachers-delete.html',
        context={'teacher': teacher}
    )


class TeacherListView(ListView):
    model = Teacher
    template_name = 'teachers-list.html'
    success_url = reverse_lazy('students:list')
    paginate_by = 10
    context_object_name = 'teachers'

    def get_filter(self):
        return TeacherFilter(
            data=self.request.GET,
            queryset=self.model.objects.all().select_related('group')
        )

    def get_queryset(self):
        return self.get_filter().qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = self.get_filter()
        context['query_params'] = self.request.GET.urlencode()

        if 'page' in self.request.GET:
            get_params = copy(self.request.GET)
            del get_params['page']
            context['query_params'] = get_params.urlencode()

        return context


class TeacherCreateView(CreateView):
    model = Teacher
    form_class = TeacherUpdateForm
    success_url = 'teachers:list'
    template_name = 'teachers-create.html'
    pk_url_kwarg = 'id'


class TeacherUpdateView(UpdateView):

    model = Teacher
    form_class = TeacherUpdateForm
    success_url = 'teachers:list'
    template_name = 'teachers-update.html'
    pk_url_kwarg = 'id'


class TeacherDeleteView(DeleteView):

    model = Teacher
    form_class = TeacherBaseForm
    success_url = 'teachers:list'
    template_name = 'teacher-delete.html'
    pk_url_kwarg = 'id'

src/teachers/templates/teachers-create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block main %}
    <form method='post'>
        {% csrf_token %}
      {{form|crispy}}
      <input type="submit" value="Create">
    </form>
{% endblock %}
{% block info %}
<h2> You're creating teachers there! </h2>
{% endblock %}

src/teachers/templates/teachers-delete.html
{% extends 'base.html' %}

{% block header %}
    <h1> Teacher delete </h1>
{% endblock %}

{% block main %}

    <form method='post'>
        {% csrf_token %}
      <h3>Do you really want to delete {{ teacher.first_name }} {{ teacher.last_name }}?</h3>

      <input type="submit" class="btn btn-danger" value="Delete">
      <a href="{% url 'teachers:list' %}" class="btn btn-light">Cancel</a>
    </form>

{% endblock %}
{% block info %}
<h2> You're deleting teachers there! </h2>
{% endblock %}

src/teachers/templates/teachers-list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block header %}
    <h1> Teachers list </h1>
{% endblock %}
{% block main %}
    <div class="p-3 m-3">
            <form method='get'>
                {% csrf_token %}
                {{ filter.form|crispy }}
                <input type="submit" class="btn btn-primary" value="Search">
                <a class="btn btn-danger" href="{% url 'teachers:list' %}">Reset</a>
            </form>
        </div>

    <br>

<!--    <table class="table table-striped table-hover">-->
<!--      <tr>-->
<!--        <th>№</th>-->
<!--        <th>First name</th>-->
<!--        <th>Last name</th>-->
<!--        <th>Age</th>-->
<!--        <th>Group</th>-->
<!--        <th>✎</th>-->
<!--        <th>🗑</th>-->
<!--      </tr>-->

<!--        {% for teacher in filter.qs %}-->
<!--              <tr>-->
<!--                <td>{{ forloop.counter0|add:page_obj.start_index }}</td>-->
<!--                <td>{{ teacher.first_name }}</td>-->
<!--                <td>{{ teacher.last_name }}</td>-->
<!--                <td>{{ teacher.age }}</td>-->
<!--                <td>{{ teacher.group.name }}</td>-->
<!--                <td><a href='{% url "teachers:update" teacher.id %}'>UPDATE</a></td>-->
<!--                <td><a href='{% url "teachers:delete" teacher.id %}'>DELETE</a></td>-->
<!--              </tr>-->
<!--        {% endfor %}-->
<!--    </table>-->
                    {% include 'includes/teachers-table.html' %}
                    {% include 'includes/paginator.html' %}
{% endblock %}
{% block info %}
<h2> You're seeing teachers there! </h2>
{% endblock %}

src/teachers/templates/teachers-update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block main %}
    <form method='post'>
        {% csrf_token %}
      {{form|crispy}}
      <input type="submit" value="Update">
    </form>
{% endblock %}
{% block info %}
<h2> You're updating teachers there! </h2>
{% endblock %}