src/lms/urls.py
from core.views import index

import debug_toolbar

from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings # noqa
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', index, name='index'),

    path('students/', include('students.urls')),
    path('accounts/', include('accounts.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('classrooms/', include('classrooms.urls')),

    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/students/urls.py
from django.conf import settings # noqa
from django.urls import include, path # noqa

from students.views import StudentCreateView, StudentDeleteView, StudentListView, StudentUpdateView

app_name = "students"

urlpatterns = [
    path('', StudentListView.as_view(), name='list'),
    path('create', StudentCreateView.as_view(), name='create'),
    path('update/<int:id>', StudentUpdateView.as_view(), name='update'),
    path('delete/<int:id>', StudentDeleteView.as_view(), name='delete'),
]

src/students/models.py
import datetime
import random

from core.models import Person

import django
from django.db import models

from faker import Faker

from groups.models import Group


class Student(Person):

    enroll_date = models.DateField(default=datetime.date.today)
    graduate_date = models.DateField(default=django.utils.timezone.now)

    group = models.ForeignKey(
        to=Group,
        null=True,
        on_delete=models.SET_NULL,
        related_name='students'
    )

    @classmethod
    def _generate(cls):
        faker = Faker()
        obj = cls(
            first_name=faker.first_name(),
            last_name=faker.last_name(),
            age=random.randint(15, 105),
            group=random.choice(list(Group.objects.all())),
        )

        obj.save()
        return object

src/students/forms.py
import re

from django.core.exceptions import ValidationError
from django.forms import ModelForm

import django_filters


from email_validator import EmailNotValidError, validate_email

from students.models import Student


class StudentFilter(django_filters.FilterSet):

    class Meta:

        model = Student
        fields = {
            'age': ['lt', 'gt'],
            'first_name': ['exact', 'icontains'],
            'last_name': ['exact', 'startswith'],
        }


class StudentBaseForm(ModelForm):

    class Meta:
        model = Student
        # fields = ['first_name', 'last_name', 'age']
        fields = '__all__'

    def as_div(self):
        "Return this form rendered as HTML <p>s."
        return self._html_output(
            normal_row='<p%(html_class_attr)s>%(label)s %(field)s%(help_text)s</p>',
            error_row='%s',
            row_ender='</p>',
            help_text_html=' <span class="helptext">%s</span>',
            errors_on_separate_row=True,
        )

    def clean_phone_number(self):
        SHORT_LENGTH = 13 # noqa

        phone_number = self.cleaned_data['phone_number']

        pattern = '(\(\d\d\d\)|\+\d\d\(\d\d\d\))\d\d\d\-\d\d\d\d' # noqa

        if not re.match(pattern, phone_number):
            raise ValidationError('Phone number is not correct')

        if len(phone_number) == SHORT_LENGTH:
            phone_number = '+38' + phone_number

        exist_students = Student.objects.filter(phone_number=phone_number).exclude(id=self.instance.id).exists()

        if exist_students:
            raise ValidationError('Email is not unique')

        return phone_number

    def clean(self):
        result = super().clean()

        enroll_date = self.cleaned_data['enroll_date']
        graduate_date = self.cleaned_data['graduate_date']

        if enroll_date > graduate_date:
            raise ValidationError('Enroll date coudn\'t be after graduate date')

        return result

    def clean_email(self):

        BLACKLIST = ['asd.com'] # noqa

        email = self.cleaned_data['email']

        try:
            valid = validate_email(email)
            email = valid.email
            domain = valid.domain
            if domain in BLACKLIST:
                raise ValidationError('Your domain is prohibited')
        except EmailNotValidError:
            raise ValidationError('Email is invalid')

        exist_students = Student.objects.filter(email=email).exclude(id=self.instance.id).exists()

        if exist_students:
            raise ValidationError('Email is not unique')

        return email


class StudentCreateForm(StudentBaseForm):
    pass


class StudentUpdateForm(StudentBaseForm):
    class Meta(StudentBaseForm.Meta):
        exclude = ['age']

src/students/views.py
# from django.contrib.auth.mixins import LoginRequiredMixin
from copy import copy

from core.views import LoginRequiredMixin

from django.utils.http import urlencode # noqa

from django.db.models import Q # noqa
from django.http import HttpResponse, HttpResponseRedirect # noqa
from django.shortcuts import get_object_or_404, render # noqa
from django.urls import reverse, reverse_lazy # noqa
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from students.forms import StudentBaseForm, StudentCreateForm, StudentFilter, StudentUpdateForm
from students.models import Student


class StudentUpdateView(LoginRequiredMixin, UpdateView):

    model = Student
    form_class = StudentUpdateForm
    success_url = reverse_lazy('students:list')
    template_name = 'students-update.html'
    pk_url_kwarg = 'id'


class StudentListView(LoginRequiredMixin, ListView):
    model = Student
    template_name = 'students-list.html'
    success_url = reverse_lazy('students:list')
    paginate_by = 50
    context_object_name = 'students'

    def get_filter(self):
        return StudentFilter(
            data=self.request.GET,
            queryset=self.model.objects.all().select_related('group', 'headed_group')
        )

    def get_queryset(self):
        return self.get_filter().qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = self.get_filter()
        # context['students'] = self.get_queryset()
        context['query_params'] = self.request.GET.urlencode()

        if 'page' in self.request.GET:
            get_params = copy(self.request.GET)
            del get_params['page']
            context['query_params'] = get_params.urlencode()

        return context


class StudentCreateView(LoginRequiredMixin, CreateView):
    model = Student
    form_class = StudentCreateForm
    success_url = reverse_lazy('students:list')
    template_name = 'students-create.html'


class StudentDeleteView(LoginRequiredMixin, DeleteView):
    model = Student
    form_class = StudentBaseForm
    success_url = reverse_lazy('students:list')
    template_name = 'students-delete.html'
    pk_url_kwarg = 'student_id'

src/students/templates/students-create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block header %}
    <h1> Student create </h1>
{% endblock %}
{% block main %}
    <form method='post'>
        {% csrf_token %}
        {{form|crispy}}
      <input type="submit" value="Create">
    </form>
{% endblock %}
{% block info %}
<h2> You're creating students there! </h2>
{% endblock %}

src/students/templates/students-delete.html
{% extends 'base.html' %}

{% block header %}
    <h1> Student delete </h1>
{% endblock %}

{% block main %}

    <form method='post'>
        {% csrf_token %}
      <h3>Do you really want to delete {{ student.first_name }} {{ student.last_name }}?</h3>

      <input type="submit" class="btn btn-danger" value="Delete">
      <a href="{% url 'students:list' %}" class="btn btn-light">Cancel</a>
    </form>

{% endblock %}
{% block info %}
<h2> You're deleting students there! </h2>
{% endblock %}

src/students/templates/students-list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block header %}
    <h1> Student list </h1>
{% endblock %}


{% block main %}

        <div class="p-3 m-3">
            <form method='get'>
                {% csrf_token %}
                {{ filter.form|crispy }}

                <input type="submit" class="btn btn-primary" value="Search">
                <a class="btn btn-danger" href="{% url 'students:list' %}">Reset</a>
            </form>
        </div>


    <br>

<!--    <table class="table table-striped table-hover">-->
<!--      <tr>-->
<!--        <th>First name</th>-->
<!--        <th>Last name</th>-->
<!--        <th>Email</th>-->
<!--        <th>Age</th>-->
<!--        <th>Group</th>-->
<!--        <th>✎</th>-->
<!--        <th>🗑</th>-->
<!--      </tr>-->

<!--          {% for student in filter.qs %}-->
<!--              <tr>-->
<!--                <td>{{ student.first_name }}</td>-->
<!--                <td>{{ student.last_name }}</td>-->
<!--                <td>{{ student.email }}</td>-->
<!--                <td>{{ student.age }}</td>-->
<!--                <td>{{ student.group.name }}</td>-->
<!--                <td><a href='{% url "students:update" student.id %}'>UPDATE</a></td>-->
<!--                <td><a href='{% url "students:delete" student.id %}'>DELETE</a></td>-->
<!--              </tr>-->
<!--        {% endfor %}-->

<!--    </table>-->
<!--    {% with students=object_list %}-->
        {% include 'includes/students-table.html' %}
        {% include 'includes/paginator.html' %}
<!--    {% endwith %}-->
{% endblock %}
{% block info %}
<h2> You're seeing students there! </h2>
{% endblock %}

src/students/templates/students-update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block header %}
    <h1> Student update </h1>
{% endblock %}
{% block main %}
    <form method='post'>
      {% csrf_token %}
      {{form|crispy}}
      <input type="submit" class="btn btn-success" value="Update">
    </form>
{% endblock %}
{% block info %}
<h2> You're updating students there! </h2>
{% endblock %}