src/classrooms/urls.py
from classrooms.views import create_classroom, delete_classroom, get_classroom, update_classroom

from django.conf import settings # noqa
from django.urls import include, path # noqa

app_name = "classrooms"

urlpatterns = [
    path('', get_classroom, name='list'),
    path('create', create_classroom, name='create'),
    path('update/<int:id>', update_classroom, name='update'),
    path('delete/<int:id>', delete_classroom, name='delete'),
]

src/lms/urls.py
from core.views import index

import debug_toolbar

from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings # noqa
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', index, name='index'),

    path('students/', include('students.urls')),
    path('accounts/', include('accounts.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('classrooms/', include('classrooms.urls')),

    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/classrooms/models.py
from django.db import models

from groups.models import Group


class Classroom(models.Model):

    name = models.CharField(max_length=64, null=False)
    group = models.ManyToManyField(
        to=Group,
        related_name='group'
    )

src/classrooms/forms.py
from classrooms.models import Classroom

from django.forms import ModelForm

import django_filters


class ClassroomFilter(django_filters.FilterSet):

    class Meta:

        model = Classroom
        fields = '__all__'


class ClassBaseForm(ModelForm):

    class Meta:
        model = Classroom
        fields = '__all__'

    def as_div(self):
        "Return this form rendered as HTML <p>s."
        return self._html_output(
            normal_row='<p%(html_class_attr)s>%(label)s %(field)s%(help_text)s</p>',
            error_row='%s',
            row_ender='</p>',
            help_text_html=' <span class="helptext">%s</span>',
            errors_on_separate_row=True,
        )


class ClassCreateForm(ClassBaseForm):
    pass


class ClassUpdateForm(ClassBaseForm):
    pass

src/classrooms/views.py
from classrooms.forms import ClassCreateForm, ClassUpdateForm, ClassroomFilter
from classrooms.models import Classroom

from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404  # noqa
from django.urls import reverse

# Create your views here.


def get_classroom(request):
    classroom = Classroom.objects.all().order_by('-id')

    filter = ClassroomFilter(  # noqa
        data=request.GET,
        queryset=classroom,
    )

    return render(
        request=request,
        template_name='classroom-list.html',
        context={'classroom': classroom}
    )


def create_classroom(request):
    if request.method == 'POST':

        form = ClassCreateForm(request.POST)

        if form.is_valid():
            form.save()

            return HttpResponseRedirect(reverse('classroom:list'))

    else:

        form = ClassCreateForm()

    return render(
        request=request,
        template_name='classroom-create.html',
        context={'form': form}
    )


def update_classroom(request, id):  # noqa
    classroom = get_object_or_404(Classroom, id=id)

    if request.method == 'POST':

        form = ClassUpdateForm(
            data=request.POST,
            instance=classroom
        )

        if form.is_valid():
            form.save()

            return HttpResponseRedirect(reverse('classroom:list'))

    else:

        form = ClassUpdateForm(instance=classroom)

    return render(request=request,
                  template_name='classroom-update.html',
                  context={
                        'form': form,
                        'classroom': classroom}
                  )

def delete_classroom(request, id):  # noqa
    classroom = get_object_or_404(Classroom, id=id)

    if request.method == 'POST':
        classroom.delete()
        return HttpResponseRedirect(reverse('classroom:list'))

    return render(
        request=request,
        template_name='classroom-delete.html',
        context={'classroom': classroom}
    )

src/classrooms/templates/classroom-create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block main %}
    <form method='post'>
        {% csrf_token %}
      {{form|crispy}}
      <input type="submit" value="Create">
    </form>
{% endblock %}
{% block info %}
<h2> You're creating classrooms there! </h2>
{% endblock %}

src/classrooms/templates/classroom-delete.html
{% extends 'base.html' %}

{% block header %}
    <h1> Classroom delete </h1>
{% endblock %}

{% block main %}

    <form method='post'>
        {% csrf_token %}
      <h3>Do you really want to delete {{ classroom.name }}?</h3>

      <input type="submit" class="btn btn-danger" value="Delete">
      <a href="{% url 'classrooms:list' %}" class="btn btn-light">Cancel</a>
    </form>

{% endblock %}
{% block info %}
<h2> You're deleting classrooms there! </h2>
{% endblock %}

src/classrooms/templates/classroom-list.html
{% extends 'base.html' %}
{% block header %}
    <h1> Classrooms list </h1>
{% endblock %}
{% block main %}
    <table class="table table-striped table-hover">
      <tr>
        <th>Name</th>
        <th>✎</th>
        <th>🗑</th>
      </tr>

        {% for class in classroom %}
              <tr>
                <td>{{ class.name }}</td>
                <td><a href='{% url "classrooms:update" class.id %}'>UPDATE</a></td>
                <td><a href='{% url "classrooms:delete" class.id %}'>DELETE</a></td>
              </tr>
        {% endfor %}

    </table>
{% endblock %}
{% block info %}
<h2> You're seeing classrooms there! </h2>
{% endblock %}

src/classrooms/templates/classroom-update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block main %}
    <form method='post'>
        {% csrf_token %}
      {{form|crispy}}
      <input type="submit" value="Update">
    </form>
{% endblock %}
{% block info %}
<h2> You're updating teachers there! </h2>
{% endblock %}